### ISSUE TITLE
git --tags to include non-annotated tags

### ISSUE THREAD

**Issue by davistan** [jennings/SemVerHarvester#10]
Hi, thanks for this tools. However, I've spent awhile to figure out why my tag is still returning 0.0.0 and the reason is I created a tag in git without annotation.

Reading from the manual, we could add `--tags` in the `git describe` command.

This will make harvester works on both annotated and non-annotated tags.

**Comment by jennings** [comment]
I can't think of a reason why we would have wanted to ignore lightweight tags. Submit a pull request and I'll merge it in.

**Comment by jennings** [comment]
Closed with #11
